In [6]:
import numpy as np
import pandas as pd

In [7]:
dataset = pd.read_csv("/content/Restaurant_Reviews.tsv", delimiter="\t", quoting=3)
dataset.head()

Review  Liked
0                           Wow... Loved this place.      1
1                                 Crust is not good.      0
2          Not tasty and the texture was just nasty.      0
3  Stopped by during the late May bank holiday of...      1
4  The selection on the menu was great and so wer...      1

In [8]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   Review  1000 non-null   object
 1   Liked   1000 non-null   int64 
dtypes: int64(1), object(1)
memory usage: 15.8+ KB


In [9]:
dataset.dtypes

Review    object
Liked      int64
dtype: object

In [10]:
dataset.groupby('Liked').size()

Liked
0    500
1    500
dtype: int64

In [11]:
dataset.isnull().sum()

Review    0
Liked     0
dtype: int64

In [12]:
dataset['Review'][0]

'Wow... Loved this place.'

In [13]:
# Removing Numbers and Punctuations
import re
review = re.sub( '[^a-zA-Z]', ' ', dataset['Review'][0] )
print(review)

Wow    Loved this place 


In [14]:
review = review.lower()
review

'wow    loved this place '

In [15]:
import nltk
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


True

In [16]:
from nltk.corpus import stopwords
print(len(stopwords.words('english')))

179


In [17]:
review

'wow    loved this place '

In [18]:
review1 = " ".join([ word for word in review.split() if not word in set(stopwords.words('english')) ])
review1

'wow loved place'

In [19]:
from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()
review1 = [ ps.stem(word) for word in review1.split() ]
review1

['wow', 'love', 'place']

In [20]:
review2 = ' '.join(review1)
review2

'wow love place'

In [21]:
corpus1 = []
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features=3)
print(review2)
corpus1.append(review2)
print(corpus1)
X = cv.fit_transform(corpus1)
print(X.toarray())

wow love place
['wow love place']
[[1 1 1]]


In [22]:
dataset.shape

(1000, 2)

In [23]:
dataset.tail()

Review  Liked
995  I think food should have flavor and texture an...      0
996                           Appetite instantly gone.      0
997  Overall I was not impressed and would not go b...      0
998  The whole experience was underwhelming, and I ...      0
999  Then, as if I hadn't wasted enough of my life ...      0

In [24]:
import re
import nltk
# nltk.download('stopwords')
from nltk.stem.porter import PorterStemmer

corpus = []
for i in range(0,1000):
    review = re.sub('[^a-zA-Z]',' ',dataset['Review'][i])
    review = review.lower()
    review = review.split()
    ps = PorterStemmer()
    review = [ ps.stem(word) for word in review if not word in set(stopwords.words('english')) ]
    review = ' '.join(review)
    print(review)
    corpus.append(review)

wow love place
crust good
tasti textur nasti
stop late may bank holiday rick steve recommend love
select menu great price
get angri want damn pho
honeslti tast fresh
potato like rubber could tell made ahead time kept warmer
fri great
great touch
servic prompt
would go back
cashier care ever say still end wayyy overpr
tri cape cod ravoli chicken cranberri mmmm
disgust pretti sure human hair
shock sign indic cash
highli recommend
waitress littl slow servic
place worth time let alon vega
like
burritto blah
food amaz
servic also cute
could care less interior beauti
perform
right red velvet cake ohhh stuff good
never brought salad ask
hole wall great mexican street taco friendli staff
took hour get food tabl restaur food luke warm sever run around like total overwhelm
worst salmon sashimi
also combo like burger fri beer decent deal
like final blow
found place accid could happier
seem like good quick place grab bite familiar pub food favor look elsewher
overal like place lot
redeem qualiti r

In [25]:
type(review)

str

In [26]:
corpus

['wow love place',
 'crust good',
 'tasti textur nasti',
 'stop late may bank holiday rick steve recommend love',
 'select menu great price',
 'get angri want damn pho',
 'honeslti tast fresh',
 'potato like rubber could tell made ahead time kept warmer',
 'fri great',
 'great touch',
 'servic prompt',
 'would go back',
 'cashier care ever say still end wayyy overpr',
 'tri cape cod ravoli chicken cranberri mmmm',
 'disgust pretti sure human hair',
 'shock sign indic cash',
 'highli recommend',
 'waitress littl slow servic',
 'place worth time let alon vega',
 'like',
 'burritto blah',
 'food amaz',
 'servic also cute',
 'could care less interior beauti',
 'perform',
 'right red velvet cake ohhh stuff good',
 'never brought salad ask',
 'hole wall great mexican street taco friendli staff',
 'took hour get food tabl restaur food luke warm sever run around like total overwhelm',
 'worst salmon sashimi',
 'also combo like burger fri beer decent deal',
 'like final blow',
 'found place acc

In [27]:
corpus_dataset = pd.DataFrame(corpus)
corpus_dataset.head()

0
0                                     wow love place
1                                         crust good
2                                 tasti textur nasti
3  stop late may bank holiday rick steve recommen...
4                            select menu great price

In [28]:
corpus_dataset['corpus'] = corpus_dataset
corpus_dataset.head()

0  \
0                                     wow love place   
1                                         crust good   
2                                 tasti textur nasti   
3  stop late may bank holiday rick steve recommen...   
4                            select menu great price   

                                              corpus  
0                                     wow love place  
1                                         crust good  
2                                 tasti textur nasti  
3  stop late may bank holiday rick steve recommen...  
4                            select menu great price

In [29]:
corpus_dataset = corpus_dataset.drop([0], axis=1)
corpus_dataset.head()

corpus
0                                     wow love place
1                                         crust good
2                                 tasti textur nasti
3  stop late may bank holiday rick steve recommen...
4                            select menu great price

In [30]:
corpus_dataset.to_csv("corpus_dataset.csv")

In [31]:
# Create a Bag of Words Model
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features=1500)

In [32]:
X = cv.fit_transform(corpus).toarray()
X[0]

array([0, 0, 0, ..., 0, 0, 0])

In [33]:
len(X[0])

1500

In [34]:
cv.get_feature_names_out()

array(['absolut', 'acknowledg', 'actual', ..., 'yum', 'yummi', 'zero'],
      dtype=object)

In [35]:
len(cv.get_feature_names_out())

1500

In [36]:
y = dataset.iloc[:,1].values
y

array([1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1,
       1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1,
       0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1,
       1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1,
       1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0,
       1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0,
       0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0,
       1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1,
       0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1,
       0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1,
       1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1,
       0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1,

In [37]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, random_state=0)

In [38]:
from sklearn.naive_bayes import GaussianNB
classifier = GaussianNB()
classifier.fit(X_train, y_train)

GaussianNB()

In [39]:
y_pred = classifier.predict(X_test)

In [40]:
from sklearn.metrics import confusion_matrix,accuracy_score

In [41]:
confusion_matrix(y_test,y_pred)

array([[55, 42],
       [12, 91]])

In [42]:
accuracy_score(y_test,y_pred)

0.73

In [43]:
Review = "nice service"
input1 = [Review]

input_data = cv.transform(input1).toarray()

input_pred = classifier.predict(input_data)

if input_pred[0]==1:
    print("Review is Positive")
else:
    print("Review is Negative")

Review is Positive


In [44]:
Review = "long waiting time"
input1 = [Review]

input_data = cv.transform(input1).toarray()

input_pred = classifier.predict(input_data)

if input_pred[0]==1:
    print("Review is Positive")
else:
    print("Review is Negative")

Review is Negative


In [45]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

for c in [0.01, 0.05, 0.25, 0.5, 1]:

    lr = LogisticRegression(penalty='l2', C=c, max_iter=7600, random_state=42)
    lr.fit(X_train, y_train)
    print ("Accuracy for C=%s: %s"
           % (c, accuracy_score(y_test, lr.predict(X_test))))

Accuracy for C=0.01: 0.715
Accuracy for C=0.05: 0.725
Accuracy for C=0.25: 0.74
Accuracy for C=0.5: 0.72
Accuracy for C=1: 0.715


In [46]:
final_model = LogisticRegression(penalty='l2', C=0.25, max_iter=7600, random_state=42)
final_model.fit(X_train, y_train)
print ("Final Accuracy: %s"
       % accuracy_score(y_test, final_model.predict(X_test)))

Final Accuracy: 0.74


In [47]:
feature_to_coef = {
    word: coef for word, coef in zip(
        cv.get_feature_names_out(), final_model.coef_[0]
    )
}
print("POSITIVE")
for best_positive in sorted(
    feature_to_coef.items(),
    key=lambda x: x[1],
    reverse=True)[:5]:
    print (best_positive)
print("NEGATIVE")
for best_negative in sorted(
    feature_to_coef.items(),
    key=lambda x: x[1])[:5]:
    print (best_negative)

POSITIVE
('great', 1.735314680759885)
('delici', 1.1341296667274012)
('love', 1.031718280046452)
('good', 0.9881285684683713)
('amaz', 0.932803563739277)
NEGATIVE
('bad', -0.7029950945494832)
('worst', -0.6655142230801441)
('minut', -0.6518001002693183)
('would', -0.6120361775393961)
('terribl', -0.5771823678253419)


In [48]:
y_pred_lr = final_model.predict(X_test)

In [49]:
from sklearn.metrics import confusion_matrix,accuracy_score

In [50]:
confusion_matrix(y_test,y_pred_lr)

array([[83, 14],
       [38, 65]])

In [51]:
accuracy_score(y_test,y_pred_lr)

0.74

In [52]:
Review = "nice service"
input1 = [Review]

input_data = cv.transform(input1).toarray()

input_pred = final_model.predict(input_data)

if input_pred[0]==1:
    print("Review is Positive")
else:
    print("Review is Negative")

Review is Positive


In [53]:
Review = "long waiting time"
input1 = [Review]

input_data = cv.transform(input1).toarray()

input_pred = final_model.predict(input_data)

if input_pred[0]==1:
    print("Review is Positive")
else:
    print("Review is Negative")

Review is Negative


# TF-IDF

In [54]:
corpus_dataset.head()

corpus
0                                     wow love place
1                                         crust good
2                                 tasti textur nasti
3  stop late may bank holiday rick steve recommen...
4                            select menu great price

In [55]:
from sklearn.feature_extraction.text import TfidfVectorizer

tfidf = TfidfVectorizer()

X = tfidf.fit_transform(corpus_dataset['corpus'])

print(tfidf.vocabulary_)
print(tfidf.idf_)

{'wow': 1547, 'love': 802, 'place': 1028, 'crust': 324, 'good': 594, 'tasti': 1362, 'textur': 1374, 'nasti': 900, 'stop': 1311, 'late': 762, 'may': 834, 'bank': 92, 'holiday': 667, 'rick': 1149, 'steve': 1304, 'recommend': 1115, 'select': 1205, 'menu': 852, 'great': 608, 'price': 1062, 'get': 578, 'angri': 33, 'want': 1497, 'damn': 333, 'pho': 1016, 'honeslti': 670, 'tast': 1360, 'fresh': 553, 'potato': 1054, 'like': 785, 'rubber': 1163, 'could': 297, 'tell': 1367, 'made': 813, 'ahead': 15, 'time': 1396, 'kept': 745, 'warmer': 1499, 'fri': 554, 'touch': 1414, 'servic': 1214, 'prompt': 1074, 'would': 1545, 'go': 588, 'back': 83, 'cashier': 213, 'care': 205, 'ever': 461, 'say': 1190, 'still': 1306, 'end': 445, 'wayyy': 1507, 'overpr': 967, 'tri': 1424, 'cape': 201, 'cod': 259, 'ravoli': 1105, 'chicken': 236, 'cranberri': 310, 'mmmm': 872, 'disgust': 384, 'pretti': 1061, 'sure': 1346, 'human': 687, 'hair': 628, 'shock': 1223, 'sign': 1234, 'indic': 709, 'cash': 211, 'highli': 660, 'waitre

In [56]:
X = X.toarray()
print(X)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [57]:
X.shape

(1000, 1565)

In [58]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, random_state=0)

In [59]:
from sklearn.naive_bayes import GaussianNB
classifier = GaussianNB()
classifier.fit(X_train, y_train)

GaussianNB()

In [60]:
y_pred = classifier.predict(X_test)

In [61]:
from sklearn.metrics import confusion_matrix,accuracy_score

In [62]:
confusion_matrix(y_test,y_pred)

array([[57, 40],
       [16, 87]])

In [63]:
accuracy_score(y_test,y_pred)

0.72

In [67]:
Review = "nice service"
input1 = [Review]

input_data = tfidf.transform(input1).toarray()

input_pred = classifier.predict(input_data)

if input_pred[0]==1:
    print("Review is Positive")
else:
    print("Review is Negative")

Review is Positive


In [68]:
Review = "long waiting time"
input1 = [Review]

input_data = tfidf.transform(input1).toarray()

input_pred = classifier.predict(input_data)

if input_pred[0]==1:
    print("Review is Positive")
else:
    print("Review is Negative")

Review is Negative


In [69]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

for c in [0.01, 0.05, 0.25, 0.5, 1]:

    lr = LogisticRegression(penalty='l2', C=c, max_iter=7600, random_state=42)
    lr.fit(X_train, y_train)
    print ("Accuracy for C=%s: %s"
           % (c, accuracy_score(y_test, lr.predict(X_test))))

Accuracy for C=0.01: 0.62
Accuracy for C=0.05: 0.73
Accuracy for C=0.25: 0.75
Accuracy for C=0.5: 0.75
Accuracy for C=1: 0.755


In [70]:
final_model = LogisticRegression(penalty='l2', C=1, max_iter=7600, random_state=42)
final_model.fit(X_train, y_train)
print ("Final Accuracy: %s"
       % accuracy_score(y_test, final_model.predict(X_test)))

Final Accuracy: 0.755


In [71]:
feature_to_coef = {
    word: coef for word, coef in zip(
        cv.get_feature_names_out(), final_model.coef_[0]
    )
}
print("POSITIVE")
for best_positive in sorted(
    feature_to_coef.items(),
    key=lambda x: x[1],
    reverse=True)[:5]:
    print (best_positive)
print("NEGATIVE")
for best_negative in sorted(
    feature_to_coef.items(),
    key=lambda x: x[1])[:5]:
    print (best_negative)

POSITIVE
('hamburg', 3.3744283568277846)
('dirti', 2.1067691985610115)
('mango', 2.05482229502413)
('anoth', 1.8326619381965905)
('groceri', 1.8326480779688474)
NEGATIVE
('beauti', -1.3884776359376434)
('tigerlilli', -1.2637225521004314)
('multipl', -1.2281388561181585)
('qualiti', -1.09655759974415)
('italian', -1.0608534587529697)


In [72]:
y_pred_lr = final_model.predict(X_test)

In [73]:
from sklearn.metrics import confusion_matrix,accuracy_score

In [74]:
confusion_matrix(y_test,y_pred_lr)

array([[85, 12],
       [37, 66]])

In [75]:
accuracy_score(y_test,y_pred_lr)

0.755

In [76]:
Review = "nice service"
input1 = [Review]

input_data = tfidf.transform(input1).toarray()

input_pred = final_model.predict(input_data)

if input_pred[0]==1:
    print("Review is Positive")
else:
    print("Review is Negative")

Review is Positive


In [77]:
Review = "long waiting time"
input1 = [Review]

input_data = tfidf.transform(input1).toarray()

input_pred = final_model.predict(input_data)

if input_pred[0]==1:
    print("Review is Positive")
else:
    print("Review is Negative")

Review is Negative


# Happy Learning